import { Product } from './types';

export const initialProducts: Omit<Product, 'id' | 'createdAt'>[] = [
  {
    nameAr: "قميص كتان كاجوال مريح",
    nameEn: "Casual Relaxed Linen Shirt",
    descriptionAr: "قميص كلاسيكي مصنوع من الكتان الطبيعي الفاخر بنسبة 100٪. مثالي للأجواء الصيفية الحارة، يوفر تهوية ممتازة وملمسًا ناعمًا على البشرة مريح ومناسب للخروجات الصباحية والمسائية.",
    descriptionEn: "Classic shirt crafted from 100% premium natural linen. Perfect for hot summer days, offering excellent breathability, a soft feel, and standard casual look.",
    price: 950,
    category: 'men',
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=600",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["#E1D7C6", "#2B5B84", "#F5F5F5", "#1E1E1E"],
    inStock: true
  },
  {
    nameAr: "هودي ستريت وير هيب هوب مريح",
    nameEn: "Streetwear Oversized Hoodie",
    descriptionAr: "هودي ثقيل ومريح ذو قصّة عريضة (أوفر سايز) ومصنوع من القطن الفاخر المبطن بالصوف الناعم من الداخل ليمنحك الدفء والمظهر العصري الرائع المناسب لفصل الشتاء.",
    descriptionEn: "Heavyweight and cozy oversized hoodie made of premium fleece-lined cotton. Designed to keep you warm with an effortless, modern streetwear vibe.",
    price: 1200,
    category: 'men',
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=600",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#2C3E50", "#111111", "#BDC3C7", "#E74C3C"],
    inStock: true
  },
  {
    nameAr: "بنطلون تشينو كلاسيك فاخر",
    nameEn: "Premium Classic Chino Pants",
    descriptionAr: "بنطلون كاجوال كلاسيك مريح للغاية مصنوع من مزيج القطن والليكرا عالي الجودة ليمنحك مرونة كاملة للاستخدام اليومي والعملي، مع قصة مستقيمة ومظهر أنيق للغاية.",
    descriptionEn: "Extremely comfortable stretch classic chino pants. Crafted from high-quality cotton-lycra blend for absolute mobility and a clean straight-fit.",
    price: 850,
    category: 'men',
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=600",
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["#D2B48C", "#4B5320", "#000080", "#2C3E50"],
    inStock: true
  },
  {
    nameAr: "فستان ساتان صيفي ساحر",
    nameEn: "Enchanting Satin Summer Dress",
    descriptionAr: "فستان نسائي أنيق مصنوع من الساتان البارد عالي الجودة مع قصة منسابة تمنحك إطلالة أنثوية باهرة في المناسبات الصيفية والمسائية الخاصة والسهرات.",
    descriptionEn: "An elegant flowing satin dress with a beautiful shape. Designed to offer a premium, elegant profile for special evening events and summers.",
    price: 1450,
    category: 'women',
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=600",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#A52A2A", "#008080", "#111111", "#D4AF37"],
    inStock: true
  },
  {
    nameAr: "جاكيت بليزر أوفر سايز راقي",
    nameEn: "Elegant Oversized Crop Blazer",
    descriptionAr: "بليزر نسائي بتصميم محدد وقصة عصرية مريحة. مناسب لتنسيقه بطريقة كاجوال مع الجينز أو لمظهر رسمي راقٍ في العمل والاجتماعات.",
    descriptionEn: "Highly sophisticated modern oversized blazer. Style it casually with denim or dress it up for an elegant, professional aesthetic.",
    price: 1650,
    category: 'women',
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&q=80&w=600",
    sizes: ["M", "L", "XL"],
    colors: ["#111111", "#FFFFFF", "#E5D3B3", "#808080"],
    inStock: true
  },
  {
    nameAr: "جونلة ماكسي صيفية مكسرة",
    nameEn: "Pleated Airy Maxi Skirt",
    descriptionAr: "جونلة نسائية طويلة خفيفة ومهواة بقصّة مكسرة (بليسيه) وحزام مطاطي مريح عند الخصر. تمنحك إحساسًا بالحيوية والأناقة مع كل خطوة.",
    descriptionEn: "Elegant flowing pleated maxi skirt featuring a comfortable elastic waistband. Adds light, playful motion and unique sophistication to your steps.",
    price: 750,
    category: 'women',
    image: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=600",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#FFC0CB", "#FFFFFF", "#36454F", "#2A52BE"],
    inStock: true
  },
  {
    nameAr: "سالوبيت قطن عضوي للأطفال",
    nameEn: "Organic Cotton Baby Romper",
    descriptionAr: "سالوبيت مصنوع من القطن العضوي فائق النعومة بنسبة 100٪ ليحمي بشرة أطفالكم الحساسة. يتميز بأزرار كبس سهلة لسرعة التغيير وتصاميم لافتة وجميلة.",
    descriptionEn: "Baby romper crafted from 100% ultra-soft organic cotton, caring for infants' delicate skin. Features snap buttons for simple, fast undressing and charming prints.",
    price: 490,
    category: 'kids',
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eb2?auto=format&fit=crop&q=80&w=600",
    sizes: ["3-6M", "6-12M", "12-18M", "18-24M"],
    colors: ["#ADD8E6", "#FFB6C1", "#F5F5DC", "#E0F7FA"],
    inStock: true
  },
  {
    nameAr: "سويت شيرت ديناصور للأطفال",
    nameEn: "Kids Dino Graphic Sweatshirt",
    descriptionAr: "سويت شيرت مبهج برسومات ديناصورات بارزة ومحببة للأطفال. مصمم ليكون متينًا ومناسبًا للعب والأنشطة المدرسية مع توفير تدفئة مثالية في الشتاء.",
    descriptionEn: "Durable and adorable child winter crewneck sweatshirt featuring fun dinosaur graphics. Specially reinforced for intense playtime, kindergarten, and school comfort.",
    price: 620,
    category: 'kids',
    image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&q=80&w=600",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
    colors: ["#2ECC71", "#3498DB", "#F39C12", "#7F8C8D"],
    inStock: true
  },
  {
    nameAr: "نظارة شمسية كلاسيك عصرية",
    nameEn: "Elegant Minimalist Sunglasses",
    descriptionAr: "نظارة شمسية راقية للجنسين تحمي من الأشعة فوق البنفسجية 100% UV400. هيكل معدني فاخر وخفيف الوزن لإطلالة جذابة وحديثة ومقاومة للخدوش الصعبة.",
    descriptionEn: "Premium unisex aviator sunglasses with absolute UV400 eyes protection. Sophisticated lightweight frame, engineered scratch-resistance, and styling.",
    price: 550,
    category: 'accessories',
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=600",
    sizes: ["One Size"],
    colors: ["#111111", "#D4AF37", "#8A9A86"],
    inStock: true
  },
  {
    nameAr: "ساعة جلد كلاسيك فخمة",
    nameEn: "Premium Legacy Leather Watch",
    descriptionAr: "ساعة يد أنيقة ذات قرص معدني من الفولاذ المقاوم للصدأ باللون الذهبي المطفي وحزام مصنوع من الجلد الطبيعي. ملائمة للمناسبات وحياتك العملية واليومية المتميزة.",
    descriptionEn: "An elegant retro analog wristwatch with matte golden brushed casing, durable mineral glass, and textured genuine leather strap. Fits both formal and smart casual styles.",
    price: 1350,
    category: 'accessories',
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=600",
    sizes: ["One Size"],
    colors: ["#8B4513", "#111111", "#000080"],
    inStock: true
  },
  {
    nameAr: "كيمونو كتان بوهيمي مريح",
    nameEn: "Linen Oversized Bohemian Kimono",
    descriptionAr: "كيمونو صيفي ناعم بتفاصيل بوهيمية وقصة مريحة واسعة، منسوج من خيوط الكتان العضوي ومثالي للارتداء فوق الملابس اليومية أو الشاطئية لإطلالة عصرية خلابة.",
    descriptionEn: "An organic pure linen bohemian styled utility kimono. Loose fit, perfect for beach coverups, evening layering, or smart everyday street luxury styling.",
    price: 1390,
    category: 'women',
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=600",
    sizes: ["S", "M", "L", "XL"],
    colors: ["#F5F5DC", "#FFFFFF", "#2E4A62", "#000000"],
    inStock: true
  },
  {
    nameAr: "جيليه كتان كلاسيكي راقي",
    nameEn: "Luxury Tailored Linen Vest",
    descriptionAr: "جيليه نسائي مبطن ذو قصة محددة وأزرار أمامية كلاسيكية، مصنوع يدويًا من الكتان الفاخر ليمنحكِ مظهرًا رائعًا بمفرده أو مع بليزر.",
    descriptionEn: "A tailored linen crop waistcoat featuring marbleized horn buttons and clean lapels. Designed to elevate trousers or skirt edits to architectural perfection.",
    price: 890,
    category: 'women',
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&q=80&w=600",
    sizes: ["XS", "S", "M", "L"],
    colors: ["#DCDCDC", "#FFFDD0", "#111111"],
    inStock: true
  },
  {
    nameAr: "جاكيت شامواه فخم وعصري",
    nameEn: "Structured Suede Utility Jacket",
    descriptionAr: "جاكيت شامواه فائق النعومة بقصة عملية مستقيمة وجيوب أمامية واسعة لإطلالة شتوية وخريفية دافئة وراقية للغاية تحاكي أرقى دور الأزياء العالمية.",
    descriptionEn: "Suede-textured utility jacket featuring micro-pile lining, brushed nickel zips, and oversized multi-pocket architecture for effortless warmth and street styling.",
    price: 1850,
    category: 'men',
    image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&q=80&w=600",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["#A0522D", "#111111", "#1C3B24"],
    inStock: true
  },
  {
    nameAr: "تيشرت قطن ثقيل مغسول",
    nameEn: "Washed Heavyweight Cotton Tee",
    descriptionAr: "تيشرت عصري بأكتاف منسدلة مصنوع من القطن المصري الثقيل بنسبة 100٪ مع تأثير مغسول معتق ليواكب صيحات الملابس الكاجوال المريحة والأنيقة.",
    descriptionEn: "Heavyweight drop-shoulder oversized graphic tee made from Egyptian carded cotton. Mineral acid washed for a worn-in, vintage streetwear look.",
    price: 590,
    category: 'men',
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=600",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["#2d3748", "#1a202c", "#718096"],
    inStock: true
  },
  {
    nameAr: "كارديجان تريكو دافئ للأطفال",
    nameEn: "Vintage Knit Cozy Cardigan",
    descriptionAr: "كارديجان تريكو دافئ وناعم للغاية منسوج من خيوط صوفية خفيفة لا تسبب الحكة، مزود بأزرار خشبية كلاسيكية ليغمر طفلك بالدفء بأناقة فائقة.",
    descriptionEn: "Unisex cozy knitted toddler cardigan made with butter-soft hypoallergenic yarns and solid organic wood toggles. Perfect for stylish seasonal layering.",
    price: 780,
    category: 'kids',
    image: "https://images.unsplash.com/photo-1622295057035-9677a23359d8?auto=format&fit=crop&q=80&w=600",
    sizes: ["1-2Y", "3-4Y", "5-6Y"],
    colors: ["#DDB892", "#9C6644", "#FFFDD0"],
    inStock: true
  },
  {
    nameAr: "طقم كتان صيفي للأطفال بشورت",
    nameEn: "Linen Beach coordenadas Shorts Set",
    descriptionAr: "طقم صيفي قطعتين (قميص وشورت مريح) مصنوع من الكتان الطبيعي الفاخر المنعش، مثالي للرحلات والخرجات الصيفية والمناسبات النهارية المبهجة.",
    descriptionEn: "Breathable linen toddler coordinates including regular fit button-up top and adjustable drawstring shorts. Ideal for breezy vacation and resort days.",
    price: 850,
    category: 'kids',
    image: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&q=80&w=600",
    sizes: ["2Y", "4Y", "6Y", "8Y"],
    colors: ["#F0F8FF", "#FFF8DC", "#FFD700"],
    inStock: true
  },
  {
    nameAr: "حقيبة يد شامواه فاخرة",
    nameEn: "Suede Elegant Leather Tote Bag",
    descriptionAr: "حقيبة يد (توت) واسعة مصنوعة من الجلد الطبيعي والشامواه الفاخر، مصممة بمساحة تخزين رحبة لحمل الكمبيوتر الشخصي والمستندات اليومية بأناقة وراحة فائقتين.",
    descriptionEn: "Spacious slouchy suede shopper tote bag featuring rich natural handles, secure gold-toned inner zips, and extra-durable reinforced structural support.",
    price: 1690,
    category: 'accessories',
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&q=80&w=600",
    sizes: ["One Size"],
    colors: ["#6F4E37", "#000000", "#A0522D"],
    inStock: true
  },
  {
    nameAr: "قلادة معدنية كلاسيكية ناعمة",
    nameEn: "Minimalist Retro Link Chain",
    descriptionAr: "قلادة للجنسين بتصميم كلاسيكي ناعم بطلاء ذهبي مقاوم للتآكل والماء، تضفي لمسة نهائية عصرية لا تضاهى على ملابسك وتلائم جميع المناسبات.",
    descriptionEn: "Waterproof minimalist stainless steel snake link chain plated in 18k gold. Designed to resist tarnish and look brilliant alone or as a layering staple.",
    price: 420,
    category: 'accessories',
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=600",
    sizes: ["One Size"],
    colors: ["#FFD700", "#C0C0C0"],
    inStock: true
  }
];
